name: HEXO自动部署

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1

      - name: 使用 Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

   
      - name: 安装依赖项
        run: |
          npm i -g hexo-cli
          npm i
      - name: 部署 hexo
        run: |
          hexo clean && hexo generate && hexo deploy
